#!/bin/bash
#SBATCH --job-name=lammps
#SBATCH --account=prezhdo_176
#SBATCH --partition=shared
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --time=25:00:00
#SBATCH --output=out_%j.log
#SBATCH --error=out_%j.err
#SBATCH --mem=0

cd $SLURM_SUBMIT_DIR
echo ${SLURM_NTASKS}

#export OMP_NUM_THREADS=1

module purge
module load intel/19.0.4
module load intel-mpi/2019.4.243
module load intel-mkl/2019.5.281
module load python/3.9.2

ulimit -s unlimited

eval "$(conda shell.bash hook)"
conda activate deepmd

mpirun -n $SLURM_NTASKS lmp -in input.in
